import type { BusinessSettings, DeviceSettings, SessionState, ShortcutMap } from '@/types/settings';
import { APP_CONFIG } from './app.config';

/* ==========================================================================
   Default settings. Persisted settings are always merged over these
   (mergeSettings), so new options appear automatically after upgrades.
   Change a default here and it applies everywhere.
   ========================================================================== */

/**
 * Keyboard shortcut defaults. Format: optional modifiers ("Mod" = Ctrl on
 * Windows/Linux, Cmd on macOS; "Alt", "Shift") joined with "+" and a key name
 * as reported by KeyboardEvent.key (letters upper-case).
 */
export const DEFAULT_SHORTCUTS: ShortcutMap = {
  goPos: 'F1',
  goProducts: 'F2',
  goSales: 'F3',
  goCustomers: 'F4',
  refresh: 'F5',
  goReports: 'F6',
  holdSale: 'F7',
  recallSale: 'F8',
  payment: 'F9',
  discount: 'F10',
  fullscreen: 'F11',
  globalSearch: 'Mod+K',
  completePayment: 'Mod+Enter',
  removeItem: 'Delete',
  increaseQty: '+',
  decreaseQty: '-',
  focusSearch: 'Mod+F',
  selectCustomer: 'Alt+C',
  clearCart: 'Mod+Delete',
  showShortcuts: 'Mod+/',
};

export const DEFAULT_DEVICE_SETTINGS: DeviceSettings = {
  appearance: {
    theme: 'dark',
    accent: 'emerald',
    density: 'comfortable',
    fontSize: 'md',
    baseFontPx: 15,
    uiFont: 'inter',
    banglaFont: 'noto-bengali',
    receiptFont: 'noto-bengali',
    corners: 'rounded',
    sidebar: 'compact',
    animations: true,
    hoverEffects: true,
    highContrast: false,
    focusMode: false,
    cardSize: 'md',
  },
  locale: {
    language: 'bn',
    numerals: 'en',
    clock: '12h',
  },
  pos: {
    layout: 'grid',
    autoFocusSearch: true,
    autoAddScanned: true,
    duplicateScanIncreasesQty: true,
    quickCheckoutOnEnter: true,
    confirmClearCart: true,
    clearCartAfterSale: true,
    showStock: true,
    showSku: true,
    showBarcode: false,
    showDiscount: true,
    showMrp: true,
    showProductImages: true,
    productImageSize: 'md',
    showCustomerPanel: true,
    showNumericKeypad: true,
    rememberLastCategory: true,
    rememberLastPaymentMethod: false,
    lastCategoryId: null,
    lastPaymentMethod: null,
    showSecondaryName: true,
  },
  barcode: {
    scanSpeedMs: APP_CONFIG.barcode.scanSpeedMs,
    minLength: APP_CONFIG.barcode.minLength,
    terminator: 'enter',
    unknownAction: 'toast',
    prefix: '',
  },
  printer: {
    receiptPrinter: '',
    reportPrinter: '',
    a4Printer: '',
    paperWidth: '80mm',
    autoPrint: false,
    showPreview: true,
    copies: 1,
    printAfterSale: false,
  },
  sound: {
    enabled: true,
    volume: 0.5,
    scan: true,
    success: true,
    error: true,
  },
  notifications: {
    lowStock: true,
    outOfStock: true,
    expiring: true,
    shiftReminder: true,
    backupReminder: true,
    largeDiscount: true,
    pendingPurchase: true,
    desktop: false,
  },
  shortcuts: DEFAULT_SHORTCUTS,
  terminal: {
    branchId: APP_CONFIG.organization.branchId,
    counterId: '',
    name: '',
  },
  general: {
    landingPage: 'auto',
    confirmExit: false,
  },
};

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  store: {
    nameBn: 'নগর সুপার শপ',
    nameEn: 'Nogor Super Shop',
    addressBn: 'ঢাকা, বাংলাদেশ',
    addressEn: 'Dhaka, Bangladesh',
    phone: '+880 1712-345678',
    email: 'hello@nogorsupershop.com.bd',
    website: 'www.nogorsupershop.com.bd',
    taxId: '004567891-0101',
    tradeLicense: 'TRAD/DNCC/045612/2026',
    logo: null,
    receiptFooterBn: 'বিক্রিত পণ্য ৭ দিনের মধ্যে রসিদসহ ফেরতযোগ্য।',
    receiptFooterEn: 'Goods can be returned within 7 days with this receipt.',
    thankYouBn: 'আমাদের সাথে কেনাকাটার জন্য ধন্যবাদ!',
    thankYouEn: 'Thank you for shopping with us!',
  },
  currency: {
    code: 'BDT',
    symbol: '৳',
    position: 'before',
    decimals: 'auto',
  },
  tax: {
    enabled: true,
    mode: 'exclusive',
    defaultRate: 500,
    rates: [0, 500, 750, 1000, 1500],
    labelBn: 'ভ্যাট',
    labelEn: 'VAT',
  },
  receipt: {
    showLogo: true,
    showCustomerName: true,
    showCustomerPhone: true,
    showLoyaltyPoints: true,
    showMembership: true,
    showBarcode: true,
    showSku: false,
    showTaxBreakdown: true,
    showSavings: true,
    showCashier: true,
    showCounter: true,
    headerNoteBn: '',
    headerNoteEn: '',
    showBin: true,
    language: 'sale',
  },
  loyalty: {
    enabled: true,
    pointsPerStep: 1,
    earnStep: 10_000,
    pointValue: 100,
    minRedeemPoints: 50,
    maxRedeemRate: 5_000,
  },
  discount: {
    allowItemDiscount: true,
    allowOrderDiscount: true,
    requireReason: true,
    cashierMaxRate: 1_000,
    managerMaxRate: 5_000,
    largeDiscountRate: 1_500,
    customerTypeRates: { regular: 0, vip: 500, wholesale: 300 },
    applyCustomerDiscountAutomatically: true,
  },
  inventory: {
    allowNegativeStock: false,
    trackExpiry: true,
    expiryAlertDays: APP_CONFIG.inventory.expiringSoonDays,
    defaultMinStock: 10,
    defaultMaxStock: 200,
  },
  sales: {
    invoicePrefix: APP_CONFIG.numbering.invoicePrefix,
    rounding: 'none',
    returnWindowDays: 7,
    cashierReturnWindowDays: 1,
    allowCancel: true,
    cancelWindowHours: 24,
  },
  payment: {
    methods: { cash: true, card: true, mobile: true },
    mobileProviders: { bkash: true, nagad: true, rocket: true, upay: true, other: true },
    quickCash: [...APP_CONFIG.pos.quickCashDefaults],
    requireCardReference: false,
    requireMobileReference: false,
    allowSplit: true,
  },
  customer: {
    requirePhone: true,
    defaultType: 'regular',
  },
  shift: {
    requireOpenShift: true,
    defaultOpeningCash: 500_000,
    maxDifference: 50_000,
    reminderHours: 10,
    blindClose: false,
  },
  security: {
    requireManagerForPriceOverride: true,
    requireManagerForLargeDiscount: true,
    requireManagerForCancel: true,
    autoLockMinutes: 0,
    pinLength: APP_CONFIG.auth.pinMinLength,
  },
};

export const DEFAULT_SESSION: SessionState = {
  firstRunCompleted: false,
  lastUserId: null,
  lastBackupAt: null,
  demoMode: true,
};
